-- Ismart Skills CRM — full schema for new installs

CREATE TABLE IF NOT EXISTS leads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NULL,
  company VARCHAR(255) NULL,
  job_title VARCHAR(255) NULL,
  enquiry_type VARCHAR(100) NULL,
  programme VARCHAR(255) NULL,
  message TEXT NULL,
  course_slug VARCHAR(255) NULL,
  course_name VARCHAR(255) NULL,
  course_category VARCHAR(100) NULL,
  page_url VARCHAR(500) NULL,
  status ENUM(
    'new','contacted','demo_scheduled','qualified','proposal_sent','enrolled','closed_lost','spam'
  ) NOT NULL DEFAULT 'new',
  notes TEXT NULL,
  assigned_to VARCHAR(100) NULL,
  follow_up_date DATE NULL,
  preferred_contact ENUM('email','phone','whatsapp') NULL,
  funding_type ENUM('self_funded','employer','government','instalment','unknown') NOT NULL DEFAULT 'unknown',
  deal_value DECIMAL(10,2) NOT NULL DEFAULT 0,
  payment_status ENUM('none','pending','deposit','partial','paid','refunded') NOT NULL DEFAULT 'none',
  enrollment_date DATE NULL,
  lost_reason VARCHAR(255) NULL,
  priority ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_leads_status (status),
  INDEX idx_leads_email (email),
  INDEX idx_leads_source (source),
  INDEX idx_leads_created (created_at),
  INDEX idx_leads_course (course_slug),
  INDEX idx_leads_follow_up (follow_up_date),
  INDEX idx_leads_assigned (assigned_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
