/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GenerativeAiCourseRouteImport } from './routes/generative-ai-course'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses_.$slug'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerativeAiCourseRoute = GenerativeAiCourseRouteImport.update({
  id: '/generative-ai-course',
  path: '/generative-ai-course',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses_/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/generative-ai-course': typeof GenerativeAiCourseRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/generative-ai-course': typeof GenerativeAiCourseRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/generative-ai-course': typeof GenerativeAiCourseRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/courses_/$slug': typeof CoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/generative-ai-course'
    | '/privacy'
    | '/security'
    | '/services'
    | '/why-choose-us'
    | '/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/generative-ai-course'
    | '/privacy'
    | '/security'
    | '/services'
    | '/why-choose-us'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/generative-ai-course'
    | '/privacy'
    | '/security'
    | '/services'
    | '/why-choose-us'
    | '/courses_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  GenerativeAiCourseRoute: typeof GenerativeAiCourseRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generative-ai-course': {
      id: '/generative-ai-course'
      path: '/generative-ai-course'
      fullPath: '/generative-ai-course'
      preLoaderRoute: typeof GenerativeAiCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$slug': {
      id: '/courses_/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  GenerativeAiCourseRoute: GenerativeAiCourseRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  CoursesSlugRoute: CoursesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
